INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy A20','Samsung','Smartphone',158);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Pixel A3','Google','Smartphone',399);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy A10','Samsung','Smartphone',128);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPhone 7','Apple','Smartphone',210);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPhone 6','Apple','Smartphone',99);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Honor 8X','Huawei','Smartphone',174);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy A50','Samsung','Smartphone',250);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Redmi Note 7','Xiaomi','Smartphone',180);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Moto G7','Motorola','Smartphone',279);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Moto G6','Motorola','Smartphone',139);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy S9','Samsung','Smartphone',420);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPhone 6S','Apple','Smartphone',169);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy S8','Samsung','Smartphone',380);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPhone XS','Apple','Smartphone',900);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPhone X','Apple','Smartphone',720);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy Note 8','Samsung','Smartphone',309);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy Note 10','Samsung','Smartphone',1000);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Pixel XL','Google','Smartphone',220);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Surface Pro 6','Microsoft','Tablet',750);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Tab 4 10.1','Lenovo','Tablet',180);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Galaxy Tab A8','Samsung','Tablet',196);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Surface Go','Microsoft','Tablet',580);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Yoga Tab 3 Pro','Lenovo','Tablet',300);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('MediaPad','Huawei','Tablet',349);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPad Pro','Apple','Tablet',799);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('iPad','Apple','Tablet',329);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Chromebook','Lenovo','Computer',219);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Predator Helios 300','Acer','Computer',1099);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Aspire','Lenovo','Computer',314);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Chromebook','Asus','Computer',215);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Zenbook','Asus','Computer',999);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Pavilion','HP','Computer',340);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Vivobook','Asus','Computer',380);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('GL63','MSI','Computer',799);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Gear 3','Samsung','Smartwatch',277);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Apple Watch S3','Apple','Smartwatch',200);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Vivoactive','Garmin','Smartwatch',179);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Versa lite','Fitbit','Smartwatch',156);
INSERT INTO PRODUCT(PRNAME,PRBRAND,PRCATEGORY,PRICE) VALUES
('Apple Watch S3','Apple','Smartwatch',200);
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Akron', '35', '(330) 947-5335');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Albuquerque', '31', '(623) 570-9473');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Anaheim', '5', '(533) 545-9776');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Anchorage', '2', '(655) 784-9602');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Arlington', '43', '(234) 428-8619');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Atlanta', '10', '(525) 246-7438');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Aurora', '6', '(793) 867-2777');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Austin', '43', '(244) 305-3309');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Bakersfield', '5', '(935) 492-0153');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Baltimore', '20', '(288) 499-2086');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Baton Rouge', '18', '(896) 597-0084');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Birmingham', '1', '(890) 605-3597');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Boise', '12', '(593) 678-9985');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Boston', '21', '(870) 729-9026');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Buffalo', '32', '(447) 598-0004');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Chandler', '3', '(750) 659-1981');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Charlotte', '33', '(519) 592-4166');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Chesapeake', '46', '(531) 396-8956');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Chicago', '13', '(861) 649-6044');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Chula Vista', '5', '(740) 478-6887');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Cincinnati', '35', '(914) 623-6225');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Cleveland', '35', '(845) 315-1108');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Colorado Springs', '6', '(739) 227-5947');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Columbus', '35', '(416) 403-6519');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Corpus Christi', '43', '(554) 861-2010');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Dallas', '43', '(648) 380-4951');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Denver', '6', '(645) 465-7942');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Detroit', '22', '(516) 293-6573');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Durham', '33', '(569) 997-2517');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('El Paso', '43', '(350) 259-8650');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Fort Wayne', '14', '(868) 466-3702');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Fort Worth', '43', '(527) 686-9452');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Fresno', '5', '(474) 910-3440');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Garland', '43', '(415) 982-7161');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Glendale', '3', '(839) 758-1917');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Greensboro', '33', '(479) 827-1906');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Henderson', '28', '(431) 312-9179');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Hialeah', '9', '(760) 361-1462');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Honolulu', '11', '(375) 887-5382');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Houston', '43', '(975) 227-2432');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Huntington', '32', '(535) 624-6569');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Indianapolis', '14', '(402) 895-9107');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Jacksonville', '9', '(789) 896-6637');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Jersey City', '30', '(419) 971-1724');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Kansas City', '25', '(375) 261-6698');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Laredo', '43', '(383) 584-8768');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Las Vegas', '28', '(463) 281-1051');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Lexington-Fayette', '17', '(791) 251-4503');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Lincoln', '27', '(797) 955-3037');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Long Beach', '5', '(640) 992-5022');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Los Angeles', '5', '(861) 987-8294');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Lubbock', '43', '(814) 331-7654');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Madison', '49', '(787) 449-6892');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Memphis', '42', '(314) 945-4374');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Mesa', '3', '(445) 244-6684');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Miami', '9', '(791) 605-8957');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Milwaukee', '49', '(489) 539-2831');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Minneapolis', '23', '(888) 855-4312');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Modesto', '5', '(206) 918-0601');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Montgomery', '1', '(205) 930-2196');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Nashville-Davidson', '42', '(693) 805-4701');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('New Orleans', '18', '(306) 557-8011');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('New York', '32', '(968) 816-0282');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Newark', '30', '(520) 757-6558');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Norfolk', '46', '(608) 782-0343');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('North Hempstead', '32', '(344) 372-6714');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Oakland', '5', '(859) 234-0868');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Oklahoma City', '36', '(527) 594-3397');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Omaha', '27', '(728) 408-6641');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Orlando', '9', '(605) 891-6574');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Philadelphia', '38', '(380) 787-9420');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Phoenix', '3', '(903) 470-0693');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Pittsburgh', '38', '(584) 567-1134');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Plano', '43', '(879) 369-2586');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Portland', '37', '(343) 835-5594');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Raleigh', '33', '(536) 395-9195');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Reno', '28', '(517) 307-1412');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Riverside', '5', '(977) 486-8270');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Rochester', '32', '(311) 789-5783');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Sacramento', '5', '(919) 661-8419');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('San Antonio', '43', '(922) 844-2356');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('San Bernardino', '5', '(663) 302-2286');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('San Diego', '5', '(994) 862-6843');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('San Francisco', '5', '(867) 805-1541');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('San Jose', '5', '(335) 950-3764');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Santa Ana', '5', '(605) 770-2844');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Scottsdale', '3', '(383) 750-1150');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Seattle', '47', '(704) 339-8353');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('St. Louis', '25', '(647) 513-7772');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('St. Paul', '23', '(655) 929-5173');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('St. Petersburg', '9', '(843) 343-8584');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Stockton', '5', '(863) 792-2769');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Tampa', '9', '(466) 863-3777');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Toledo', '35', '(726) 414-2767');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Tucson', '3', '(682) 806-8507');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Tulsa', '36', '(712) 232-2141');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Virginia Beach', '46', '(429) 341-6617');
INSERT INTO BRANCH(BRANCHNAME,BRANCHSTATE,BRPHONENUMBER) VALUES
('Wichita', '16', '(976) 314-7353');
