-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 03:22:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `idcustomer` INT NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(45) NOT NULL,
  `CustomerLastName` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcustomer`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `idstaff` INT NOT NULL,
  `StuffName` VARCHAR(45) NOT NULL,
  `StaffLastName` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstaff`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `idorder` INT NOT NULL AUTO_INCREMENT,
  `OrderDate` DATE NULL,
  `ShipmentDate` DATE NULL,
  `ShipmentStatus` VARCHAR(45) NULL,
  `customer_idcustomer` INT NOT NULL,
  `staff_idstaff` INT NOT NULL,
  PRIMARY KEY (`idorder`),
  INDEX `fk_order_customer1_idx` (`customer_idcustomer` ASC) VISIBLE,
  INDEX `fk_order_staff1_idx` (`staff_idstaff` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `mydb`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_staff1`
    FOREIGN KEY (`staff_idstaff`)
    REFERENCES `mydb`.`staff` (`idstaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`softwareproduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`softwareproduct` (
  `idsoftwareproduct` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Producer` VARCHAR(45) NULL,
  `ReleaseYear` YEAR NULL,
  `SaleMedium` VARCHAR(45) NULL,
  PRIMARY KEY (`idsoftwareproduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salesline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`salesline` (
  `idsalesline` INT NOT NULL AUTO_INCREMENT,
  `AmountofPurchase` INT NULL,
  `PricePerAmount` DOUBLE NULL,
  `softwareproduct_idsoftwareproduct` INT NOT NULL,
  `order_idorder` INT NOT NULL,
  PRIMARY KEY (`idsalesline`),
  INDEX `fk_salesline_softwareproduct1_idx` (`softwareproduct_idsoftwareproduct` ASC) VISIBLE,
  INDEX `fk_salesline_order1_idx` (`order_idorder` ASC) VISIBLE,
  CONSTRAINT `fk_salesline_softwareproduct1`
    FOREIGN KEY (`softwareproduct_idsoftwareproduct`)
    REFERENCES `mydb`.`softwareproduct` (`idsoftwareproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_salesline_order1`
    FOREIGN KEY (`order_idorder`)
    REFERENCES `mydb`.`order` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contactaddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contactaddress` (
  `idcontactaddress` INT NOT NULL,
  `city` VARCHAR(45) NULL,
  `Neighbourhood` VARCHAR(45) NULL,
  `Street` VARCHAR(45) NULL,
  `Number` VARCHAR(45) NULL,
  `customer_idcustomer` INT NOT NULL,
  PRIMARY KEY (`idcontactaddress`, `customer_idcustomer`),
  INDEX `fk_contactaddress_customer_idx` (`customer_idcustomer` ASC) VISIBLE,
  CONSTRAINT `fk_contactaddress_customer`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `mydb`.`customer` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`staffaddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staffaddress` (
  `idstaffaddress` INT NOT NULL,
  `City` VARCHAR(45) NULL,
  `Neighbourhood` VARCHAR(45) NULL,
  `Street` VARCHAR(45) NULL,
  `Number` VARCHAR(45) NULL,
  `staff_idstaff` INT NOT NULL,
  PRIMARY KEY (`idstaffaddress`, `staff_idstaff`),
  INDEX `fk_staffaddress_staff1_idx` (`staff_idstaff` ASC) VISIBLE,
  CONSTRAINT `fk_staffaddress_staff1`
    FOREIGN KEY (`staff_idstaff`)
    REFERENCES `mydb`.`staff` (`idstaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
